set(LINENOISE_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/linenoise")
set(LINENOISE_INCLUDE_DIRS ${LINENOISE_INCLUDE_DIR})
set(LINENOISE_LIBRARY "LINENOISE")
set(LINENOISE_LIBRARIES ${LINENOISE_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LINENOISE DEFAULT_MSG LINENOISE_LIBRARIES LINENOISE_INCLUDE_DIR LINENOISE_INCLUDE_DIRS)

mark_as_advanced(LINENOISE_LIBRARY LINENOISE_LIBRARIES LINENOISE_INCLUDE_DIR LINENOISE_INCLUDE_DIRS)
