set(EASY_PROFILER_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/easy_profiler")
set(EASY_PROFILER_INCLUDE_DIR "${EASY_PROFILER_ROOT_DIR}/easy_profiler_core/include")
set(EASY_PROFILER_INCLUDE_DIRS "${EASY_PROFILER_INCLUDE_DIR}")
set(EASY_PROFILER_LIBRARY "easy_profiler")
set(EASY_PROFILER_LIBRARIES "${EASY_PROFILER_LIBRARY}")

add_subdirectory("${EASY_PROFILER_ROOT_DIR}")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(easy_profiler DEFAULT_MSG
  EASY_PROFILER_LIBRARIES EASY_PROFILER_INCLUDE_DIRS)

mark_as_advanced(
  EASY_PROFILER_LIBRARY EASY_PROFILER_LIBRARIES
  EASY_PROFILER_INCLUDE_DIR EASY_PROFILER_INCLUDE_DIRS)
