set(FAKE_IT_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/FakeIt/single_header/catch")
set(FAKE_IT_INCLUDE_DIRS ${FAKE_IT_INCLUDE_DIR})
set(FAKE_IT_LIBRARY "")
set(FAKE_IT_LIBRARIES ${FAKE_IT_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args( DEFAULT_MSG FAKE_IT_LIBRARIES FAKE_IT_INCLUDE_DIR FAKE_IT_INCLUDE_DIRS)

mark_as_advanced(FAKE_IT_LIBRARY FAKE_IT_LIBRARIES FAKE_IT_INCLUDE_DIR FAKE_IT_INCLUDE_DIRS)

