set(CHAISCRIPT_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/chaiScript")
set(CHAISCRIPT_INCLUDE_DIR "${CHAISCRIPT_ROOT_DIR}/include/")
set(CHAISCRIPT_INCLUDE_DIRS ${CHAISCRIPT_INCLUDE_DIR})
set(CHAISCRIPT_LIBRARY "stdlib")
set(CHAISCRIPT_LIBRARIES dl ${CHAISCRIPT_LIBRARY})

add_subdirectory("${CHAISCRIPT_ROOT_DIR}")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CHAISCRIPT DEFAULT_MSG CHAISCRIPT_LIBRARIES CHAISCRIPT_INCLUDE_DIR CHAISCRIPT_INCLUDE_DIRS)

mark_as_advanced(CHAISCRIPT_LIBRARY CHAISCRIPT_LIBRARIES CHAISCRIPT_INCLUDE_DIR CHAISCRIPT_INCLUDE_DIRS)
