set(CATCH_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/catch/single_include")
set(CATCH_INCLUDE_DIRS ${CATCH_INCLUDE_DIR})
set(CATCH_LIBRARY "CATCH")
set(CATCH_LIBRARIES ${CATCH_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CATCH DEFAULT_MSG CATCH_LIBRARIES CATCH_INCLUDE_DIR CATCH_INCLUDE_DIRS)

mark_as_advanced(CATCH_LIBRARY CATCH_LIBRARIES CATCH_INCLUDE_DIR CATCH_INCLUDE_DIRS)
